// <auto-generated />
using System;
using DataAnnotations.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAnnotations.Migrations
{
    [DbContext(typeof(ChatContext))]
    partial class ChatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAnnotations.Models.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.Property<int?>("UserID");

                    b.HasKey("PermissionID");

                    b.HasIndex("UserID");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("DataAnnotations.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("RoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("DataAnnotations.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleID");

                    b.Property<int>("PermissionID");

                    b.HasKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("DataAnnotations.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("RoleID");

                    b.Property<int?>("RoleID1");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.HasIndex("RoleID1");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAnnotations.Models.Permission", b =>
                {
                    b.HasOne("DataAnnotations.Models.User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("DataAnnotations.Models.RolePermission", b =>
                {
                    b.HasOne("DataAnnotations.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataAnnotations.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAnnotations.Models.User", b =>
                {
                    b.HasOne("DataAnnotations.Models.Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID");

                    b.HasOne("DataAnnotations.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID1");
                });
#pragma warning restore 612, 618
        }
    }
}
